### ISSUE TITLE
Split according to transaction date (and transaction type)

### ISSUE THREAD

**Issue by stevieflow** [davidmegginson/iatisplit#2]
I have a large file, and would like to split out activities that contain a ``transaction`` with a ``transaction-date/@iso-date`` on or after a specified date

Added bonus, if I can also specify the ``transaction-type`` in the query, it'd be very helpful

For example:

- Split out all activities that have an Outgoing Commitment (code=2) transaction-type transaction *and* a transaction-date/@iso-date on or after 20180930

Thanks

**Comment by davidmegginson** [comment]
Implemented basic transaction filtering. Note the following new command-line options:

*--transaction-type=TYPE* - include only activities with at least one transaction of the specified type.

*--transaction-start-date=YYYY-MM-DD* - include only activities with at least one transaction on or after the specified date (after filtering by --transaction-type, if specified).

*--transaction-end-date=YYYY-MM-DD* - include only activities with at least on transaction before or on the specified date (after filtering by --transaction-type, if specified).

**Comment by davidmegginson** [comment]
@stevieflow - please test, and then close the issue if the new functionality is working for you.

**Comment by stevieflow** [comment]
Thanks @davidmegginson !

I'm not quite getting results - using the following:

> iatisplit -n 1000 -transaction-type 2 -transaction-start-date 2018-09-30 inputfile.xml


Could you post an example , please?

**Comment by davidmegginson** [comment]
The options you posted should split into groups of 1,000 activities (max), including both humanitarian and non-humanitarian activities, but only when they have at least one transaction of type "2" with a transaction date on or after 2018-09-30. What are you seeing?

Note that you need double hyphens at the beginning of the long options, so ``--transaction-type`` and ``--transaction-start-date``

**Comment by davidmegginson** [comment]
Additional question: currently, the script is filtering activities by transaction, but when a matching transaction is found, it includes the activity with _all_ its transactions. Were you looking at filtering the transactions themselves, as well?

**Comment by stevieflow** [comment]
Thanks @davidmegginson 

OK - using 

> iatisplit -n 1000 --transaction-type 2 --transaction-start-date 2018-08-30 --verbose iati-activities-Humanitarian.xml

I get

> iatisplit: error: unrecognized arguments: --transaction-type --transaction-start-date 2018-08-30 iati-activities-Humanitarian.xml

And then for just 

> iatisplit -n 1000 --transaction-type 2 --verbose iati-activities-Humanitarian.xml

I get

> iatisplit: error: unrecognized arguments: --transaction-type iati-activities-Humanitarian.xml

In terms of the other question:

> Were you looking at filtering the transactions themselves, as well?

Nope.  Getting back the whole activity, which will *contain* qualifying transactions, but all others, would be fine

**Comment by davidmegginson** [comment]
What OS are you using, @stevieflow ?

Can you try installing the latest version (0.4) and then run

```
iatisplit --version
```

to confirm?

**Comment by stevieflow** [comment]
Im on 0.4 now - which looks to have resolved it!

Thanks @davidmegginson - I've successfully filtered and split
